apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::058264090525:role/eksctl-spot-cluster-nodegroup-spot-NodeInstanceRole-7Dth5KONCFy9
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
      - userarn: arn:aws:iam::058264090525:user/roboshop-admin
        username: roboshop-admin
kind: ConfigMap
metadata:
  creationTimestamp: "2024-08-15T09:12:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1588"
  uid: 13066f84-48e1-4b65-bda0-eecacacb80c4