apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::058264090525:role/eksctl-spot-cluster-nodegroup-spot-NodeInstanceRole-8ay2hwXhM331
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::058264090525:user/roboshop-admin
      username: roboshop-admin
kind: ConfigMap
metadata:
  creationTimestamp: "2024-08-16T15:39:50Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1292"
  uid: 86ca07c5-ffaf-4d04-884d-c2a7a1b9ab5d
